project:
  type: website

website:
  title: "Nathaniel Yomogida"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: experience.qmd
        text: Experience

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



